create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    role varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    constraint users_role_check check (role in ('CUSTOMER', 'SHOP_OWNER'))
);

create table shops (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references users(id),
    name varchar(255) not null,
    description text,
    contact_info varchar(255),
    category varchar(255)
);

create table categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    parent_id bigint references categories(id),
    slug varchar(255) not null unique
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    variant varchar(255),
    description text,
    category_id bigint not null references categories(id),
    image_url varchar(1000)
);

create table product_offers (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id),
    shop_id bigint not null references shops(id),
    price numeric(12, 2) not null,
    available boolean not null default true,
    stock_quantity integer not null default 0,
    created_at timestamp not null default current_timestamp,
    constraint product_shop_unique unique (product_id, shop_id)
);

create table reviews (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references users(id),
    target_type varchar(20) not null,
    target_id bigint not null,
    rating integer not null,
    created_at timestamp not null default current_timestamp,
    constraint reviews_target_type_check check (target_type in ('PRODUCT', 'SHOP')),
    constraint reviews_rating_check check (rating between 1 and 5)
);

create index idx_products_category on products(category_id);
create index idx_offers_product on product_offers(product_id);
create index idx_offers_shop on product_offers(shop_id);
create index idx_reviews_target on reviews(target_type, target_id);
